### PR TITLE
Update Red Hat logo on website

### PR DESCRIPTION
**Pull request by Fryguy**
@castastrophe Please review.

Before:
Overpass Font - Mozilla Firefox 2020-03-13 17-00-44

After:
Overpass Font - Mozilla Firefox 2020-03-13 16-59-42

### CODE REVIEW

**Comment by Fryguy** [comment]
Most of the CSS manipulation in here is because previously some style was on the entire `.footer`, which includes the RH logo plus those other logos, but it didn't actually affect the old RH logo. When I dropped the new logo in, all of the colors were messed up and hovering turned it completely white.  The changes in this PR move that functionality to the `.award` class which is what the other logos are.

**Comment by Fryguy** [comment]
Bump? @castastrophe

**Comment by castastrophe** [comment]
@Fryguy Awesome updates!  Sorry it took so long for me to get to this PR; I've been pulled into other projects.  👍

**Comment by Fryguy** [comment]
No worries!  Thank you! 😊

**Pull request merged**
