### PR TITLE
chore: build release 3.0.4

### PR DESCRIPTION
**Pull request by teleyinex**
All the work has been done by @kosmosjamaa. This just uses the fonts built and uploaded by kosmosjamaa to Mediafire as a PR for easily fixing it upstream.

### CODE REVIEW

**Review by andyfitz — APPROVED** [review]
Wow this is embarrassingly late,  

Thank you for the updated build,  it works for me.

**Comment by andyfitz** [comment]
@castastrophe  anyone back at Red Hat able to merge this ?

When I moved this repo over and left Red Hat I lost access to it.

**Comment by bproffitt** [comment]
@andyfitz I'll merge it. Want me to add you back in here?

**Comment by michaelfaith** [comment]
How do the downstream providers/hosts get updated?  E.g. google fonts  Forgive my ignorance

**Comment by michaelfaith** [comment]
Should close this issue: https://github.com/RedHatOfficial/Overpass/issues/75

**Comment by michaelfaith** [comment]
@bproffitt does there need to be a new tag for this update? The zip attached to 3.0.4 has the old webfont files. That's likely going to throw off downstream consumers

**Comment by andyfitz** [comment]
@bproffitt @castastrophe  I no longer have access to remediate the release issue.  
Are you able to take @michaelfaith 's advice to amend the latest release with the updates?

**Comment by michaelfaith** [comment]
@bproffitt @castastrophe any chance of getting this resolved soon?  There's a pending issue Google Fonts github, to update their copies of the font, which they've queued up to work on, but I'm afraid if they grab the last release, it won't include this bug fix, which we've been waiting for for a long time.  The 3.0.4 tag doesn't include the updated webfont files.  If they take that package we'll still be at square one with this.

**Comment by bproffitt** [comment]
I am not a maintainer on this repo, just the organization. Can you check with @jimmac ?

**Comment by michaelfaith** [comment]
@bproffitt thanks getting back.  I just sent him an email to see if he can help with it.

**Comment by jimmac** [comment]
I'm afraid I'm not the savior you're looking for. No admin rights here either.

**Comment by michaelfaith** [comment]
@bproffitt is there someone else that would able to help?

**Comment by DelveFonts** [comment]
Hi Everyone, I'm Delve Withrington. I think I may be able to help but github is not my forté so I need some direction on how to do what is needed for this.

**Comment by michaelfaith** [comment]
@DelveFonts thanks for jumping in.  @andyfitz mentioned possibly amending the existing 3.0.4 release, and he may be able to share what he meant there.  The easiest thing, though, might just be to tag master with a new 3.0.5 tag, and closing out this issue: https://github.com/RedHatOfficial/Overpass/issues/75

**Comment by michaelfaith** [comment]
Here's some details on creating and editing releases:  https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

**Comment by DelveFonts** [comment]
@michaelfaith Thank you for the insight and the links concerning managing releases. I'm reviewing all of this now to get a handle on it before I make any changes. I don't want to break anything. 😱

**Comment by michaelfaith** [comment]
It looks like Google's starting to move on their side.  It got assigned to someone earlier today.  
image

@DelveFonts let me know if you need any more help with this.

**Comment by DelveFonts** [comment]
@michaelfaith Sorry for the delay. Thanks for pointing out the new activity over on GF. A question came up that I need clarification on: Did someone already export the webfonts after v3.0.4 with the line-height issue corrected? If so, where are those? Otherwise, I'll do that for a v3.0.5 release.

**Comment by michaelfaith** [comment]
@DelveFonts this PR merged in the post-3.0.4 webfonts (https://github.com/RedHatOfficial/Overpass/pull/84/files)  So, I think it should be good since the PR merged.  But it was merged after the release was made, so the new release should effectively be 3.0.4 + this PR.

**Comment by michaelfaith** [comment]
@DelveFonts any luck with this?

**Comment by michaelfaith** [comment]
@bproffitt @castastrophe  can someone _please_ do this release?  Has this repo become abandoned?

**Comment by DelveFonts** [comment]
@michaelfaith I've published the v3.0.5 release: https://github.com/RedHatOfficial/Overpass/releases/tag/v3.0.5  is anything missing or incorrect?

**Comment by michaelfaith** [comment]
@DelveFonts thanks for closing the loop on this.  Really appreciate it.  The release looks good.  You should also be able to close this issue out now:  https://github.com/RedHatOfficial/Overpass/issues/75

**Comment by DelveFonts** [comment]
😅 Yay! Thanks for confirming @michaelfaith. #75 is now closed.

**Pull request merged**
